name: "3D Print Queue"
description: "Queue d'impression 3D familiale - Liens MakerWorld uniquement"
version: "0.2.0"
slug: "3d_print_queue"
url: "https://github.com/gubas/ha_3Dqueue"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: "Interface web de la queue d'impression"
webui: "http://[HOST]:[PORT:5000]"
startup: application
boot: auto
options:
  todo_list: "todo.impressions_3d"
schema:
  todo_list: str
image: "ghcr.io/guillaume-flace/{arch}-addon-3d-print-queue"
